#Auteurs


# Liste des Auteurs
GET http://127.0.0.1:8000/api/auteur-list

# Récupération de tous les auteurs avec tri par id croissant 
 GET http://127.0.0.1:8000/api/auteur-id/55

 //récupération des auteur triés par noms
  GET http://127.0.0.1:8000/api/auteur-name

 //récupération des auteurs avec tri par ordre croissant sur le prénom
  GET http://127.0.0.1:8000/api/auteur-firstname

  //créé un auteur 
   POST http://127.0.0.1:8000/api/auteur-nouveau

   //suprimer un auteur 
   DELETE  http://127.0.0.1:8000/api/auteur-delete/{id}






