# Liste des Utilisateur:
//GET http://127.0.0.1:8000/api/utilisateur

#Ajout des utilisateur
POST  http://127.0.0.1:8000/api/utilisateur/nouveau

{
"id": "",
"nom": "PALAKOT",
"prenoms" : "IGOR",
"adresse": "vILLEjUIF",
"email": "ipalkot@mail.fr",
"login": "iplkt", 
"password": "iplkt",
"photo": "",
"phone": 1212121,
"age": 100
  }
